services:
  jobsearch:
    image: ghcr.io/klocekian/jobsearch:latest
    container_name: jobsearch
    restart: unless-stopped
    volumes:
      - jobsearch-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jobsearch.rule=Host(`jobs.fieldlines.org`)"
      - "traefik.http.routers.jobsearch.entrypoints=websecure"
      - "traefik.http.routers.jobsearch.tls.certresolver=letsencrypt"
      - "traefik.http.services.jobsearch.loadbalancer.server.port=3000"

volumes:
  jobsearch-data:

networks:
  default:
    name: proxy
    external: true
